### ISSUE TITLE
[Enhancement] 蜜柑计划站点支持

### ISSUE THREAD

**Issue by Abcuders** [ShaoxiongXu/M-Team-to-qBittorrent#1]
* 你好，我是[AutoAnimeMV](https://github.com/Abcuders/AutoAnimeMv)开发者，因为我的项目需要 [蜜柑计划：新一代的动漫下载站](https://mikanani.me/)  站点的支持，我可以fork pr一下吗

**Comment by ShaoxiongXu** [comment]
抱歉，能力有限！

**Comment by Abcuders** [comment]
> 抱歉，能力有限！

我的意思是我想贡献代码

**Comment by ShaoxiongXu** [comment]
[蜜柑计划：新一代的动漫下载站](https://mikanani.me/) 站点的支持
我觉得因该新开一个脚本把，你可以fork复用下载代码。并且已经有脚本能够自动识别网页种子链接，并在链接旁边插入按钮。兼容所有网页。

**Comment by Abcuders** [comment]
> [蜜柑计划：新一代的动漫下载站](https://mikanani.me/) 站点的支持
> 我觉得因该新开一个脚本把，你可以fork复用下载代码。并且已经有脚本能够自动识别网页种子链接，并在链接旁边插入按钮。兼容所有网页。

好的好的
