### ISSUE TITLE
bug，一直“重命名”，图标位置不对。

### ISSUE THREAD

**Issue by w316525096** [ShaoxiongXu/M-Team-to-qBittorrent#14]
Firefox 130
![image](https://github.com/user-attachments/assets/f356c813-089b-4a49-9cda-3d2d8b939292)
1）qb 没有设置密码，配置里面不填密码就一直提示要配置。
2）成功下载种子后，一直“重命名中...”。建议使用默认名字。
3）`qbittorrent 下载` 图标位置不对，即使在刷新页面之后。

**Comment by ShaoxiongXu** [comment]
1）qb 没有设置密码，配置里面随便填吧
2）成功下载种子后，一直“重命名中...”，估计是你qb里面种子没下载成功。（逻辑是检测到你成功添加到了qb才会重命名）
3）qbittorrent 下载 图标位置可以设置。

**Comment by w316525096** [comment]
1）✔
2）成功下载种子后，一直“重命名中...”，又测试了下，种子确实正在下载，还是提示”重命名中...“。
正在下载的文件可以重命名吗？
3）请问怎么设置。

**Comment by ShaoxiongXu** [comment]
2）可以 F12 看看有没有报错吧，重复下载的话由于名字改过了可能找不到种子，导致重命名失败，你换个新种子下载试试看咯。
3）![image](https://github.com/user-attachments/assets/dec41613-bbe5-423d-b0e1-fd7fd4f471b6)

**Comment by w316525096** [comment]
2）菜鸟 is here。
3）右浮按钮已经勾上了，不能拖动啊。

**Comment by ShaoxiongXu** [comment]
拖不动的。。。
