### ISSUE TITLE
提示 TypeError: Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by e4rlj** [ShaoxiongXu/M-Team-to-qBittorrent#3]
![image](https://github.com/ShaoxiongXu/M-Team-to-qBittorrent/assets/13192320/7a3bb6e9-1d5e-43e8-9303-61f8cd6654fc)

**Comment by e4rlj** [comment]
![image](https://github.com/ShaoxiongXu/M-Team-to-qBittorrent/assets/13192320/7987358c-8da0-4936-ab14-f86041d2621c)
![image](https://github.com/ShaoxiongXu/M-Team-to-qBittorrent/assets/13192320/dc641d87-a8d6-4593-90bd-9f75801c8fdd)

**Comment by ShaoxiongXu** [comment]
没法复现哦, 可否 浏览器 F12 看看 Console
