### ISSUE TITLE
hdsky.me用不了

### ISSUE THREAD

**Issue by buttt5460** [ShaoxiongXu/M-Team-to-qBittorrent#5]
hdsky.me网站能识别,但没有"点击这里进行配置"选项

**Comment by ShaoxiongXu** [comment]
> hdsky.me网站能识别,但没有"点击这里进行配置"选项

没号，测不了呀，F12 看看报什么错误！

**Comment by dadinet** [comment]
![微信截图_20240411210751](https://github.com/ShaoxiongXu/M-Team-to-qBittorrent/assets/131777059/e7d8b0da-5f1d-4b77-b16a-23eb8f128ab7)
大佬 我也是想反映这个问题 您看下上面空的控制台截图 看看可以适配不 并且 大聪明 哥 老不可说也需要适配（请原谅我不能说站名）

并且我今天自己把ios safari qb无法添加种子的问题用GPT解决了 pc端正常
GM_xmlhttpRequest部分 改成

                let data = '';
                for (let pair of formData.entries()) {
                    data += `${pair[0]}=${pair[1]}&`;
                }
                data = data.slice(0, -1);  // 去掉最后一个 "&"


                GM_xmlhttpRequest({
                    method: 'POST',
                    url: `${config.address}/api/v2/torrents/add`,
                    data: data,
                    onload: async function (response) {
                        const responseData = response.responseText;
                        if (responseData !== "Ok.") {
                            downloadMsg();
                            reject(`添加种子失败: ${responseData}`);
                        } else {
                            await sleep(1000)
                            downloadMsg();
                            resolve("添加种子成功.");
                        }
                    },
                    onerror: function (error) {
                        downloadMsg();
                        console.error('添加种子失败: 请求发生错误:', error);
                        reject("添加种子失败: 请求发生错误...");
                    }
                });
                
就正常了 应该是手机端环境不能解析formData内容 抓包const body = [object Object]; 是这样的没有数据，经过上面代码解析出来直接发送就可以正常使用了

并且对于脚本我觉得大佬做的过于细致了
1、对于PT玩家我感觉不需要进行改种子名字的操作（可能导致辅种失败）直接进行下载即可，或者增加展开按钮 在进行修改 否则就按种子名称直接下载 跳过重命名操作
2、配置页面增加种子自动管理开关（只设置分类名，无需添加路径）  这样QB里面移动分类 种子也能自动移动路径方便管理，还有一种多一次请求的方法，就是在点击下载弹出窗口的时候 通过api读取Qb的分类 然后选择分类进行下载

以上建议只是个人愚见，具体逻辑还是以大佬为主！看得出来大佬付出了很大的精力！大佬辛苦了！

**Comment by ShaoxiongXu** [comment]
已适配
